const MAX_HASHTAGS = 5;
const MAX_SYMBOLS = 20;
const COMMENT_MAX_LENGTH = 140;

const SCALE_STEP = 0.25;

const ALERT_SHOW_TIME = 5000;

export { MAX_HASHTAGS, MAX_SYMBOLS, COMMENT_MAX_LENGTH, SCALE_STEP, ALERT_SHOW_TIME };
